Traceback (most recent call last):
  File "C:\Users\Danny Han\Desktop\alphazero-sudoku\main.py", line 39, in <module>
    main()
  File "C:\Users\Danny Han\Desktop\alphazero-sudoku\main.py", line 34, in main
    data = get_trajectories(net, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny Han\Desktop\alphazero-sudoku\Trajectories.py", line 57, in get_trajectories
    data += p.playGame()
            ^^^^^^^^^^^^
  File "C:\Users\Danny Han\Desktop\alphazero-sudoku\Play.py", line 17, in playGame
    pi = self.mcts.getActionProb(board, temp=self.args['temp'])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny Han\Desktop\alphazero-sudoku\MCTS.py", line 38, in getActionProb
    for i in range(self.args.numMCTSSims):
                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'numMCTSSims'